problems/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from problems import views
from problems.views import ApiLogin

urlpatterns = [
    url(r'^register/$', views.problem_registration, name='problem_registration'),
    url(r'^status/$', views.check_status, name='check_status'),
    url(r'^districts/$', views.DistrictList.as_view()),
    url(r'^states/$', views.StateList.as_view()),
    url(r'^apiregistrer/$', views.APIProblemRegistration.as_view()),
    url(r'^guidelines/$', views.guidelines_page, name="guidelines_page"),
    url(r'^legislation/women/$', views.women_related_legislation, name="legislation_women"),
    url(r'^legislation/child/$', views.child_related_legislation, name="legislation_child"),
    url(r'^legislation/other/$', views.other_related_legislation, name="legislation_other"),
    url(r'^about/icds$', views.about_icds, name="about_icds"),
    url(r'^slider/upload_image/$', views.upload_slider_image, name="upload_image"),
    url(r'^add/generate_key/$', views.generate_creation_key, name="add_user"),
    url(r'^enroll/', views.add_user, name="enroll_user"),
    url(r'^user_auto_complete/$', views.UserHeadsAutoComplete.as_view(), name='user_auto_complete'),
    url(r'^assign_portfolio/$', views.assign_portfolio, name='assign_portfolio'),
    url(r'^problems/education/$', views.education_problems, name='education_problems'),
    url(r'^problems/electricity/$', views.electricity_problems, name='electricity_problems'),
    url(r'^problems/food/$', views.food_problems, name='food_problems'),
    url(r'^problems/clothing/$', views.clothing_problems, name='clothing_problems'),
    url(r'^problems/finance/$', views.finance_problems, name='finance_problems'),
    url(r'^problems/hospital/$', views.hospital_problems, name='hospital_problems'),
    url(r'^problems/transport/$', views.transport_problems, name='transport_problems'),
    url(r'^problems/maintanence/$', views.maintanence_problems, name='maintanence_problems'),
    url(r'^problems/cleanliness/$', views.cleanliness_problems, name='cleanliness_problems'),
    url(r'^problems/change_status/([0-9]+)/([0-9]+)/$', views.change_status, name='change_status'),
    url(r'^problems/check_status_api/$', views.StatusAPI.as_view(), name='check_status_api'),
    url(r'^api/login/$', ApiLogin.as_view(),name="api_login"),
    url(r'^change_validity/([0-9]+)/$', views.change_validity,name="change_validity"),

]

theme/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from theme import views

urlpatterns = [
    url(r'^$',views.home,name='home'),
    url(r'^dashboard/$',views.dashboard,name='dashboard')
]

wcdevelopment/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import login as login, logout as logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('theme.urls')),
    url(r'^problems/',include('problems.urls')),
    url(r'^login/$',login,name='login'),
    url(r'^logout/$',logout,name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

problems/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class State(models.Model):
    name = models.CharField(max_length=255)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class District(models.Model):
    name = models.CharField(max_length=255)
    status = models.BooleanField(default=True)
    state = models.ForeignKey(State,null=True,blank=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Problem(models.Model):
    EDUCATION = 0
    ELECTRICITY = 1
    HOSPITAL = 2
    FOOD = 3
    CLEANLINESS = 4
    CLOTHING = 5
    TRANSPORT = 6
    FINANCE = 7
    MAINTENANCE = 8
    ZERO_TO_SEVEN = 0
    EIGHT_TO_FIFTEEN = 1
    SIXTEEN_TO_TWENTYTWO = 2
    TWENTYTHREE_TO_THIRTY = 3
    ABOVE_30 = 4
    SEEN = 1
    SUBMITTED = 0
    PROGRESS = 2
    COMPLETED = 3
    STATUS_CHOICES = ((SUBMITTED,'Submitted'),(SEEN,'Seen'),(PROGRESS,'Progress'),(COMPLETED,'Completed'))
    CATEGORY_CHOICES = ((EDUCATION, "Education"), (ELECTRICITY, 'Electricity'), (HOSPITAL, 'Hospital'), (FOOD, 'Food'),
                        (CLEANLINESS, 'Cleanliness'), (CLOTHING, 'Clothing'), (TRANSPORT, 'Transport'),
                        (FINANCE, 'Finance'), (MAINTENANCE, 'Maintenance'))

    AGE_CHOICES = ((ZERO_TO_SEVEN, '0-7'), (EIGHT_TO_FIFTEEN, '8-15'), (SIXTEEN_TO_TWENTYTWO, '16-22'),
                   (TWENTYTHREE_TO_THIRTY, '23-30'),(ABOVE_30,'Above 30'))

    category = models.IntegerField(choices=CATEGORY_CHOICES, default=EDUCATION)
    state = models.ForeignKey(State,related_name='problem_state',null=True)
    district = models.ForeignKey(District,related_name='problem_district',null=True)
    anganwadi_centres = models.CharField(max_length=255)
    age = models.IntegerField(choices=AGE_CHOICES,default=ZERO_TO_SEVEN)
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='problem_images/',null=True,blank=True)
    description = models.TextField(max_length=2000)
    hash_key = models.CharField(max_length=255,null=True,blank=True)
    status = models.IntegerField(choices=STATUS_CHOICES,default=SUBMITTED)
    created_at = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    email = models.EmailField(null=False)
    is_valid_problem = models.BooleanField(blank=True,default=False)

    def __unicode__(self):
        return '%s' % (self.get_category_display)

    @property
    def district_name(self):
        return self.district.name

    @property
    def state_name(self):
        return self.state.name


class SliderImage(models.Model):
    image = models.ImageField()
    status = models.BooleanField(default=True)

class CreationKey(models.Model):
    key = models.CharField(max_length=2500,null=True,blank=True)
    status = models.BooleanField(default=True)

problems/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import datetime

from dal import autocomplete
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User, AnonymousUser, Group
from django.shortcuts import render, redirect

# Create your views here.
from rest_framework.response import Response
from rest_framework.views import APIView

from problems.forms import ProblemRegistrationForm, UploadImage, AddUser, GenerationKeyForm, AssignPortfolioForm
from problems.models import Problem, District, State, CreationKey
from problems.serializers import DistrictSerializer, StateSerializer, ProblemSerializer
from problems.templatetags.admin_menu import is_admin


def problem_registration(request):
    hash_key = None
    forms = ProblemRegistrationForm()
    if request.method == "POST":
        forms = ProblemRegistrationForm(request.POST, request.FILES)
        if forms.is_valid():
            problem = forms.save()
            messages.add_message(request, messages.SUCCESS, "Registered Successfully!  " + str(problem.hash_key))
            forms = ProblemRegistrationForm()
            hash_key = str(problem.hash_key)
    return render(request, 'problems/register.html', {'forms': forms,'hash_key_value':hash_key})


def check_status(request):
    problem = None
    if request.method == "POST":
        key = request.POST['key']

        try:
            problem = Problem.objects.get(hash_key=key,is_valid_problem=True)

        except:
            messages.add_message(request, messages.ERROR, "No such registration occured!")

    return render(request, 'problems/check_status.html', {'problem': problem})


class ApiLogin(APIView):
    def post(self, request):
        data = request.data
        username = data['username']
        password = data['password']
        try:
            user = User.objects.get(username=username)
            if user.check_password(password):
                authority = 'user'
                groups = user.groups.all()
                if Group.objects.get(name="Admin Group") in groups:
                    return Response(
                    {'id': user.id, 'email': user.username, 'name': user.first_name,
                     'status': 'success','authority':'admin'})
                elif Group.objects.get(name="education_group") in groups:
                    return Response(
                        {'id': user.id, 'email': user.username, 'name': user.first_name,
                         'status': 'success','authority':'education head' })
                elif Group.objects.get(name="maintanence_group") in groups:
                    return Response(
                        {'id': user.id, 'email': user.username, 'name': user.first_name,
                         'status': 'success','authority':'maintanence head' })
                elif Group.objects.get(name="finance_group") in groups:
                    return Response(
                        {'id': user.id, 'email': user.username, 'name': user.first_name,
                         'status': 'success','authority':'finance head' })
                elif Group.objects.get(name="transport_group") in groups:
                    return Response(
                        {'id': user.id, 'email': user.username, 'name': user.first_name,
                         'status': 'success','authority':'transport head' })
                elif Group.objects.get(name="clothing_group") in groups:
                    return Response(
                        {'id': user.id, 'email': user.username, 'name': user.first_name,
                         'status': 'success', 'authority':'clothing head'})
                elif Group.objects.get(name="cleanliness_group") in groups:
                    return Response(
                        {'id': user.id, 'email': user.username, 'name': user.first_name,
                         'status': 'success','authority':'cleanliness head' })
                elif Group.objects.get(name="food_group") in groups:
                    return Response(
                        {'id': user.id, 'email': user.username, 'name': user.first_name,
                         'status': 'success','authority':'food head' })
                elif Group.objects.get(name="hospital_group") in groups:
                    return Response(
                        {'id': user.id, 'email': user.username, 'name': user.first_name,
                         'status': 'success','authority':'hospital head' })
                elif Group.objects.get(name="electricity_group") in groups:
                    return Response(
                        {'id': user.id, 'email': user.username, 'name': user.first_name,
                         'status': 'success','authority':'electricity head' })

            else:
                return Response({'status': 'error', 'message': 'User/Password Incorrect!!'}, status=400)
        except User.DoesNotExist:
            return Response({'status': 'error', 'message': 'User/Password Incorrect!!'}, status=400)

    def get(self, request):
        if isinstance(request.user, AnonymousUser):
            return Response({'message': 'Username / Password is wrong!!', 'status': 'error'}, status=400)
        else:
            user = request.user
            return Response(
                {'user': 1})


class APIProblemRegistration(APIView):
    def post(self, request):

        data = request.data
        try:
            problem = Problem()
            problem.category = data['category']
            state = State.objects.get(id=int(data['state']))
            problem.state = state
            district = District.objects.get(id=int(data['district']))
            problem.district = district
            problem.anganwadi_centres = data['anganwadi_centres']
            problem.age = data['age']
            problem.title = data['title']
            problem.image = data['image']
            problem.description = data['description']
            name = str(problem.title)[:4]
            hash_val = str(hash(datetime.now()))[:3]
            problem.hash_key = name + hash_val
            problem.save()
            return Response(
                {'status': 'success', 'message': 'Registration Successful!!', 'unique_key': problem.hash_key})
        except Exception as e:
            return Response({'status': e, 'message': 'Registration is not possible now!!'}, status=404)


class DistrictList(APIView):
    serializer_class = DistrictSerializer

    def get(self, request):
        districts = District.objects.filter(status=True)
        serializer = self.serializer_class(districts, many=True)
        return Response(serializer.data)


class StateList(APIView):
    serializer_class = StateSerializer

    def get(self, request):
        states = State.objects.filter(status=True)
        serializer = self.serializer_class(states, many=True)
        return Response(serializer.data)


def guidelines_page(request):
    return render(request, 'problems/guidelines.html')


def women_related_legislation(request):
    return render(request, 'problems/women_related_legislation.html')


def child_related_legislation(request):
    return render(request, 'problems/child_related_legislation.html')


def other_related_legislation(request):
    return render(request, 'problems/other_legislation.html')


def about_icds(request):
    return render(request, 'problems/about_icds.html')


@user_passes_test(is_admin)
def upload_slider_image(request):
    form = UploadImage()
    if request.method == "POST":
        form = UploadImage(request.POST, request.FILES)
        print(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Uploaded Image Successfully!')
            return redirect('upload_image')
    return render(request, 'problems/upload_image.html', {'forms': form})


def add_user(request):
    akey = request.GET.get('akey')
    print(akey)
    if not CreationKey.objects.filter(status=True, key=akey).exists():
        return render(request, 'problems/error.html')
    forms = AddUser()
    if request.method == "POST":
        forms = AddUser(request.POST)
        if forms.is_valid():
            user = forms.save()
            key = CreationKey.objects.get(key=akey, status=True)
            key.status = False
            key.save()
            messages.add_message(request, messages.SUCCESS, "User added successfully!")
    return render(request, 'problems/add_user.html', {'forms': forms})


@user_passes_test(is_admin)
def generate_creation_key(request):
    forms = GenerationKeyForm()
    if request.method == "POST":
        forms = GenerationKeyForm(request.POST)
        if forms.is_valid():
            creation_key = forms.save()
            return render(request, 'problems/generate_user.html', {'forms': forms, 'creation_key': creation_key})
    return render(request, 'problems/generate_user.html', {'forms': forms})


class UserHeadsAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        query_set = User.objects.all()
        if self.q:
            query_set = query_set.filter(first_name__icontains=self.q)
        return query_set


def assign_portfolio(request):
    forms = AssignPortfolioForm()
    if request.method == "POST":
        forms = AssignPortfolioForm(request.POST)
        if forms.is_valid():
            assign = forms.save()
            messages.add_message(request, messages.SUCCESS, "Portfolio Assigned!!")
    return render(request, 'problems/assign_portfolio.html', {'forms': forms})


def education_problems(request):
    problems = Problem.objects.filter(category=Problem.EDUCATION,is_valid_problem=True).order_by('-created_at')
    seen_count = Problem.objects.filter(category=Problem.EDUCATION, status=Problem.SEEN,is_valid_problem=True).count()

problems/templates/problems/admin_dashboard.html
{% extends 'theme/index.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block banner %}
    <br>
    <br>
    <br>
    <br>
    <style>
        .card-img-bottom {
            color: #fff;
            height: 4rem;

            background: url("https://use.fontawesome.com/releases/v5.0.10/svgs/solid/anchor.svg") no-repeat;

        }

        .card-img-left {
            color: #fff;
            height: 4rem;

            background: url("https://use.fontawesome.com/releases/v5.0.10/svgs/solid/eye.svg") no-repeat;

        }

        .card-img-right {
            color: #fff;
            height: 4rem;

            background: url("https://use.fontawesome.com/releases/v5.0.10/svgs/solid/tasks.svg") no-repeat;

        }

        .card-img-top {
            color: #fff;
            height: 4rem;

            background: url("https://use.fontawesome.com/releases/v5.0.10/svgs/solid/thumbs-up.svg") no-repeat;

        }


    </style>

    <br>
    <br>
    <div class="col-lg-8" style="margin-left: 15%">
        <section>
            <div class="container">
                <div class="card">
                    <div class="row">
                        <div class="col-md-1">
                            <div class="card-block">
                                <p class="card-title">Total</p>
                                <h4 class="card-text">{{ problems.count }}</h4>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-img-bottom">
                                <i class="fas fa-anchor"></i>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-block">
                                <p class="card-title">Seen</p>
                                <h4 class="card-text">{{ seen_count }}</h4>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-img-left">
                                <i class="fas fa-anchor"></i>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-block">
                                <p class="card-title">Progress</p>
                                <h4 class="card-text">{{ progressing_count }}</h4>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-img-right">
                                <i class="fas fa-anchor"></i>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-block">
                                <p class="card-title">Completed</p>
                                <h4 class="card-text">{{ completed_count }}</h4>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-img-top">
                                <i class="fas fa-anchor"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="flex-banner">
        <ul class="slides">
            <div class="col-lg-8" style="margin-left: 15%">
                <br><br>

                <table id="mydataTable" class="display table table-striped" style="widows:100%;">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Category</th>
                        <th>Title</th>
                        <th>District</th>
                        <th>State</th>
                        <th>Age</th>
                        <th>Image</th>
                        <th>Description</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in problems %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ i.get_category_display }}</td>
                            <td>{{ i.title }}</td>
                            <td>{{ i.district.name }}</td>
                            <td>{{ i.state.name }}</td>
                            <td>{{ i.get_age_display }}</td>
                            {% if i.image %}
                                <td><img src="{{ i.image.url }}" style="width:100%;height: 25%;"></td>
                            {% else %}
                                <td><img
                                        src="https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg"
                                        style="width:100%;height: 25%;"></td>
                            {% endif %}
                            <td>{{ i.description }}</td>
                            <td>{{ i.get_status_display }}</td>
                            <td><a class="btn btn-primary" href="{% url 'change_status' i.id 1 %}">Seen</a> &nbsp;&nbsp;&nbsp;
                                <a href="{% url 'change_status' i.id 2 %}" class="btn btn-primary">Progress</a>
                                &nbsp;&nbsp;&nbsp; <a href="{% url 'change_status' i.id 3 %}" class="btn btn-primary">Completed</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </ul>
    </div>
    <script>

    </script>
    <script>
        $(document).ready(function () {
            $('#mydataTable').DataTable();
        });
    </script>
{% endblock %}

problems/templates/problems/assign_portfolio.html
{% extends 'theme/index.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block banner %}
<br>
<br>
<div id="banner">
    <div class="flex-banner">
        <ul class="slides">
            {% crispy forms %}
        </ul>
    </div>
</div>
{% endblock %}

problems/templates/problems/categorised_problems.html
{% extends 'theme/index.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block banner %}
    <br>
    <br>
    <br>
    <br>
    <style>
        .card-img-bottom {
            color: #fff;
            height: 4rem;

            background: url("https://use.fontawesome.com/releases/v5.0.10/svgs/solid/anchor.svg") no-repeat;

        }

        .card-img-left {
            color: #fff;
            height: 4rem;

            background: url("https://use.fontawesome.com/releases/v5.0.10/svgs/solid/eye.svg") no-repeat;

        }

        .card-img-right {
            color: #fff;
            height: 4rem;

            background: url("https://use.fontawesome.com/releases/v5.0.10/svgs/solid/tasks.svg") no-repeat;

        }

        .card-img-top {
            color: #fff;
            height: 4rem;

            background: url("https://use.fontawesome.com/releases/v5.0.10/svgs/solid/thumbs-up.svg") no-repeat;

        }


    </style>

    <br>
    <br>
    <div class="col-lg-8" style="margin-left: 15%">
        <section>
            <div class="container">
                <div class="card">
                    <div class="row">
                        <div class="col-md-1">
                            <div class="card-block">
                                <p class="card-title">Total</p>
                                <h4 class="card-text">{{ problems.count }}</h4>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-img-bottom">
                                <i class="fas fa-anchor"></i>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-block">
                                <p class="card-title">Seen</p>
                                <h4 class="card-text">{{ seen_count }}</h4>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-img-left">
                                <i class="fas fa-anchor"></i>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-block">
                                <p class="card-title">Progress</p>
                                <h4 class="card-text">{{ progressing_count }}</h4>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-img-right">
                                <i class="fas fa-anchor"></i>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-block">
                                <p class="card-title">Completed</p>
                                <h4 class="card-text">{{ completed_count }}</h4>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="card-img-top">
                                <i class="fas fa-anchor"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="flex-banner">
        <ul class="slides">
            <div class="col-lg-8" style="margin-left: 15%">
                <br><br>

                <table id="mydataTable" class="display table table-striped" style="widows:100%;">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Category</th>
                        <th>Title</th>
                        <th>District</th>
                        <th>State</th>
                        <th>Age</th>
                        <th>Image</th>
                        <th>Description</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in problems %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ i.get_category_display }}</td>
                            <td>{{ i.title }}</td>
                            <td>{{ i.district.name }}</td>
                            <td>{{ i.state.name }}</td>
                            <td>{{ i.get_age_display }}</td>
                            {% if i.image %}
                                <td><img src="{{ i.image.url }}" style="width:100%;height: 25%;"></td>
                            {% else %}
                                <td><img
                                        src="https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg"
                                        style="width:100%;height: 25%;"></td>
                            {% endif %}
                            <td>{{ i.description }}</td>
                            <td>{{ i.get_status_display }}</td>
                            <td><a class="btn btn-primary" href="{% url 'change_status' i.id 1 %}">Seen</a> &nbsp;&nbsp;&nbsp;
                                <a href="{% url 'change_status' i.id 2 %}" class="btn btn-primary">Progress</a>
                                &nbsp;&nbsp;&nbsp; <a href="{% url 'change_status' i.id 3 %}" class="btn btn-primary">Completed</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </ul>
    </div>
    <script>

    </script>
    <script>
        $(document).ready(function () {
            $('#mydataTable').DataTable();
        });
    </script>
{% endblock %}

problems/templates/problems/check_status.html
{% extends 'theme/index.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block banner %}
<br>
<br>
<div id="banner">
    <div class="flex-banner">
        <ul class="slides">
            <div class="container">

                <form method="post" class="form-inline">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="key">Key Value:</label>
                        <input type="text" class="form-control" id="key" placeholder="Enter the generated Key" name="key">
                    </div>
                    <br>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
            <div class="container">
                {% if problem %}
                <table id="mydataTable" class="display table table-striped" style="widows:100%;">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Category</th>
                        <th>Title</th>
                        <th>District</th>
                        <th>State</th>
                        <th>Age</th>
                        <th>Image</th>
                        <th>Description</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>

                        <tr>
                            <td>1</td>
                            <td>{{ problem.get_category_display }}</td>
                            <td>{{ problem.title }}</td>
                            <td>{{ problem.district.name }}</td>
                            <td>{{ problem.state.name }}</td>
                            <td>{{ problem.get_age_display }}</td>
                            {% if problem.image %}
                                <td><img src="{{ problem.image.url }}" style="width:100%;height: 25%;"></td>
                            {% else %}
                                <td><img
                                        src="https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg"
                                        style="width:100%;height: 25%;"></td>
                            {% endif %}
                            <td>{{ problem.description }}</td>
                            <td>{{ problem.get_status_display }}</td>
                        </tr>

                    </tbody>
                </table>
                {% endif %}
            </div>
        </ul>
    </div>
</div>
{% endblock %}

problems/templates/problems/register.html
{% extends 'theme/index.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block banner %}
    <br>
    <br>
    <div id="banner">
        <div class="flex-banner">
            <ul class="slides">
                {% crispy forms %}
            </ul>
        </div>
        {% if hash_key_value %}
            <p id="has_key_value" style="display: none">{{ hash_key_value }}</p>
        {% endif %}
    </div>
{% endblock %}

problems/templates/problems/upload_image.html
{% extends 'theme/index.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block banner %}
<br>
<br>
<div id="banner">
    <div class="flex-banner">
        <ul class="slides">
            {% crispy forms %}
        </ul>
    </div>
</div>
{% endblock %}